version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          TERM: xterm-256color
      - image: circleci/postgres:9.6.2
    working_directory: ~/Base
    steps: 
      - checkout # checkout code to working directory
      - setup_remote_docker
      - run
        command: |
          pip install -r requirements.txt
      - run
        name: Run tests
        command: |
          pytest

  deploy:
    docker:
      - image: circleci/python:3.6.4
        environment:
          TERM: xterm-256color
      - image: circleci/postgres:9.6.2
    working_directory: ~/Base
    steps: 
      - checkout # checkout code to working directory
      - setup_remote_docker
      - run
        command: |
          pip install -r requirements.txt
      - run
        name: Run tests
        command: |
          pytest
      - run
        name: Make a build
        command: |
          make build
      - run
        name: Release application docker image
        command: |
          make release





      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

        